apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
type: Opaque
data:
  # admin
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
   name: influx
spec:
   ports:
   - port: 8086
     targetPort: 8086
     name: influx
   - port: 3000
     targetPort: 3000
     name: grafana
   type: LoadBalancer
   selector:
     app: influx
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: influx
   labels:
      app: influx
spec:
   selector:
     matchLabels:
        app: influx
   template:
     metadata:
       labels:
         app: influx
     spec:
       volumes:
       - name: grafana-config
         configMap:
           name: grafana-config
       containers:
       - name: influx
         image: influxdb
         ports:
         - containerPort: 8086
       - name: grafana
         envFrom:
         - secretRef:
            name: grafana-creds
         image: grafana/grafana
         ports:
         - containerPort: 3000
         volumeMounts:
         - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yml
           name: grafana-config
           readOnly: true
           subPath: influxdb-datasource.yml
         - mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yml
           name: grafana-config
           readOnly: true
           subPath: grafana-dashboard-provider.yml
         - mountPath: /var/lib/grafana/dashboards/dashboard-usage-server.json
           name: grafana-config
           readOnly: true
           subPath: dashboard-usage-server.json