apiVersion: v1
kind: Service
metadata:
   name: influx
spec:
   ports:
   - port: 8086
     targetPort: 8086
     name: influx
   type: LoadBalancer
   externalIPs:
   
   selector:
     app: influx
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: influx
   labels:
      app: influx
spec:
   replicas: 2
   selector:
     matchLabels:
        app: influx
   template:
     metadata:
       labels:
         app: influx
     spec:
       containers:
       - name: influx
         image: influxdb
         ports:
         - containerPort: 8086
