apiVersion: apps/v1
kind: Deployment
metadata:
   name: client
   labels:
      app: client
spec:
   replicas: 2
   selector:
      matchLabels:
        app: client
   template:
     metadata:
       labels:
         app: client
     spec:
       containers:
       - name: client
         image: gitlab.ilabt.imec.be:4567/brvdvyve/live-open-data-benchmark-experiment1-client
         terminationMessagePolicy: FallbackToLogsOnError
         env:
         - name: MODE
           value: "polling" # polling or pubsub
         - name: CLIENTSIDE_CACHING
           value: "true" # only applicable with polling
         - name: NODE_ENV
           value: "dev"
         - name: POLLING_INTERVAL
           value: "100"
         - name: SERVER_SERVICE_PORT
           value: "1234" # 4443 without nginx, 1234 with nginx
         resources:
          requests:
            memory: "110Mi"
            cpu: "40m"
          limits:
            memory: "150Mi"
            cpu: "60m"
