apiVersion: v1
kind: Service
metadata:
   name: server
   labels:
     app: server
spec:
   ports:
   - port: 4444
     targetPort: 4444
   type: LoadBalancer
   selector:
     app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: server
   labels:
      app: server
spec:
   replicas: 1
   selector:
      matchLabels:
        app: server
   template:
     metadata:
       labels:
         app: server
     spec:
       containers:
       - name: server
         image: gitlab.ilabt.imec.be:4567/brvdvyve/live-open-data-benchmark-experiment1-server
         ports:
         - containerPort: 4444
         env:
         - name: NODE_ENV
           value: "production"
         resources:
          requests:
            memory: "250Mi"
            cpu: "1"
          limits:
            memory: "500Mi"
            cpu: "2"
